package edu.udea.apuntado.view;
import edu.udea.apuntado.model.Carta;
import edu.udea.apuntado.model.Jugador;
import javax.swing.*;
import java.awt.*;

/**
 * @author Pedro Arango Sánchez
 * @author David Andrés Montoya Castaño
 * @course Técnicas de Programación y Laboratorio [2554307 - G01] 
 */
public class FrmJuego extends JFrame {
    
    private static final int NUMERO_DE_JUGADORES=2;
    private boolean estaJuegoIniciado;
    private boolean estaJugador1Verificado;
    private boolean estaJugador2Verificado;
    
        
    
    private Jugador[] jugadores=new Jugador[NUMERO_DE_JUGADORES];
    /**
     * Creates new form FrmJuego
     */
    public FrmJuego() {
        initComponents();
        iniciarJugadores();
        estaJuegoIniciado=false;
        estaJugador1Verificado=false;
        estaJugador2Verificado=false;
        
    }
    
    private void iniciarJugadores(){
        for(int i=0; i<jugadores.length;i++) 
            jugadores[i]=new Jugador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRepartir = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        tpJugadores = new javax.swing.JTabbedPane();
        pnlJugador1 = new javax.swing.JPanel();
        pnlJugador2 = new javax.swing.JPanel();
        btnCalcularPuntaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apuntado");
        setLocationByPlatform(true);
        setResizable(false);

        btnRepartir.setText("Repartir");
        btnRepartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepartirActionPerformed(evt);
            }
        });

        btnVerificar.setText("Voltear cartas");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        tpJugadores.setMinimumSize(new java.awt.Dimension(160, 65));

        pnlJugador1.setBackground(new java.awt.Color(0, 145, 63));
        pnlJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlJugador1Layout = new javax.swing.GroupLayout(pnlJugador1);
        pnlJugador1.setLayout(pnlJugador1Layout);
        pnlJugador1Layout.setHorizontalGroup(
            pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        pnlJugador1Layout.setVerticalGroup(
            pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );

        tpJugadores.addTab("Pedro Arango", pnlJugador1);

        pnlJugador2.setBackground(new java.awt.Color(0, 145, 63));
        pnlJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlJugador2Layout = new javax.swing.GroupLayout(pnlJugador2);
        pnlJugador2.setLayout(pnlJugador2Layout);
        pnlJugador2Layout.setHorizontalGroup(
            pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        pnlJugador2Layout.setVerticalGroup(
            pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );

        tpJugadores.addTab("David Montoya", pnlJugador2);

        btnCalcularPuntaje.setText("Obtener puntaje");
        btnCalcularPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPuntajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRepartir)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalcularPuntaje)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepartir)
                    .addComponent(btnVerificar)
                    .addComponent(btnCalcularPuntaje))
                .addGap(18, 18, 18)
                .addComponent(tpJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRepartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepartirActionPerformed
        Carta.reiniciarBaraja();
        for(int i=0; i<jugadores.length;i++) 
            jugadores[i].repartir(); 
        jugadores[0].mostrar(pnlJugador1, true); 
        jugadores[1].mostrar(pnlJugador2, true);
        estaJuegoIniciado=true;
        estaJugador1Verificado=false;
        estaJugador2Verificado=false;
    }//GEN-LAST:event_btnRepartirActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        int pestaña=tpJugadores.getSelectedIndex(); 
                
        if(!estaJuegoIniciado)
            mostrarAlerta("Avispate pues", "Como difícil ver las cartas sin sacarlas de la baraja... reparta y que gracias!");   
        
        if(pestaña==0){
            estaJugador1Verificado=true;
            jugadores[0].mostrar(pnlJugador1, false); 
        }else if(pestaña==1){
            estaJugador2Verificado=true;
            jugadores[1].mostrar(pnlJugador2, false);}
        
        JOptionPane.showMessageDialog(new JFrame(), jugadores[pestaña].obtenerFiguras());
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnCalcularPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPuntajeActionPerformed
        int pestaña=tpJugadores.getSelectedIndex();
        
        if(!estaJuegoIniciado)
            mostrarAlerta("Póngase las pilas", "Don atembado quiere obtener puntos sin haber repartido");   

        if(pestaña==0 && !estaJugador1Verificado ||pestaña==1 && !estaJugador2Verificado ){
            mostrarAlerta("Cambie de dealer por favor", "No sabía que sos bruj@ para saber el puntaje sin voltear las cartas");
        }else{
            JOptionPane.showMessageDialog(new JFrame(), jugadores[pestaña].obtenerPuntosJugador());
        }

    }//GEN-LAST:event_btnCalcularPuntajeActionPerformed

    private void mostrarAlerta(String title, String message) {
    JOptionPane.showMessageDialog(null, message, title, JOptionPane.WARNING_MESSAGE);}

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularPuntaje;
    private javax.swing.JButton btnRepartir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JPanel pnlJugador1;
    private javax.swing.JPanel pnlJugador2;
    private javax.swing.JTabbedPane tpJugadores;
    // End of variables declaration//GEN-END:variables
}
